api/urls.py
from django.urls import path, include
from .views import PostsModelViewset, UserLists
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"posts", PostsModelViewset, basename="posts")
router.register(r"users", UserLists, basename="users")

urlpatterns = [
    path("v1/", include(router.urls)),
    path("v1/drf-auth/", include("rest_framework.urls")),
]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from forum import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Сайт-журнал"

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

app_name = "users"

urlpatterns = [
    path("login/", views.user_login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.user_register.as_view(), name="register"),
    path("register/", views.user_register.as_view(), name="register"),
    path(
        "password_change/", views.user_password_change.as_view(), name="password_change"
    ),
    path(
        "password_change_done/",
        views.user_password_change_done.as_view(),
        name="password_change_done",
    ),
    path("profile/<int:pk>", views.user_profile.as_view(), name="profile"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.forms import ValidationError


class login_form(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}),
)
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )
    class Meta:
        model = get_user_model()
        fields = ["username", "password"]
        labels = {"username": "username", "password": "password"}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control",}),
            "password": forms.PasswordInput(attrs={"class": "form-control",}),
        }


class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}), label="Password"
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        label="Repeat password",
    )

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]
        labels = {
            "username": "username",
            "email": "Email",
            "first_name": "First name",
            "last_name": "Last name",
            "password1": "Password",
            "password2": "Repeat password",
        }
        widgets = {
            "username": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "first_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
        }

   #  def clean_password1(self):
   #      if self.cleaned_data["password1"] != self.cleaned_data["password2"]:
   #          return ValidationError("Пароли не совпадают")
   #      return self.cleaned_data["password1"]

    def clean_email(self):
        if get_user_model().objects.filter(email=self.cleaned_data["email"]).exists():
            return ValidationError("Пользователь с таким email уже существует")
        else:
            return self.cleaned_data["email"]

class UserProfileForm(forms.ModelForm):
    username = forms.CharField(
        disabled=True, widget=forms.TextInput(attrs={"class": "form-control"})
    )
    email = forms.CharField(
        disabled=True, widget=forms.EmailInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
        ]
        widgets = {
            "username": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "first_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
        }
        labels = {
            "username": "username",
            "email": "Email",
            "first_name": "First name",
            "last_name": "Last name",
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Old password",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )
    new_password2 = forms.CharField(
        label="New password confirmation",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView
from .forms import UserRegistrationForm, login_form, UserProfileForm, UserPasswordChangeForm
from main.utils import DataMixin


class user_login(DataMixin, LoginView):
    form_class = login_form
    template_name = "users/login.html"
    selected = "login"
    title = "Login"
    success_url = reverse_lazy("index")


class user_register(DataMixin, CreateView):
    form_class = UserRegistrationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")
    selected = "Registration"
    title = "Register"

#  def form_valid(self, form):
#     f = form.save(commit=False)
#     f.set_password(form.cleaned_data["password1"])
#     f.save()
#     return super().form_valid(form)


class user_profile(DataMixin, UpdateView):
    form_class = UserProfileForm
    template_name = "users/profile.html"
    pk_url_kwarg = "pk"
    selected = "Profile"
    title = "Profile"

    def get_object(self, queryset = ...):
        return self.request.user
    def get_success_url(self):
        return reverse("users:profile", args=[self.request.user.pk])


# def user_login(request):
#     if request.method == "POST":
#         form = login_form(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(
#                 request, username=cd["username"], password=cd["password"]
#             )
#             if user and user.is_active:
#                 login(request, user)
#                 return redirect("index")
#             else:
#                 return render(request, "users/login.html", {"form":form, "title": "login"})
#     else:
#         form = login_form()
#         return render(request, "users/login.html", {"form":form, "title": "login", "selected":"login"})


# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse("users:login"))


class user_password_change(DataMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change.html"
    selected = "Profile"
    title = "Password change"

class user_password_change_done(DataMixin, PasswordChangeDoneView):
    template_name = "users/password_change_done.html"
    title = "Password change done"

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">{{ title }}</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.as_p }}
	              <div class="form-group">
	                <input type="submit" value="login" class="btn btn-primary py-3 px-5">
	              </div>
					<a href={% url "users:password_reset" %}>Forgot your password</a>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/password_change.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">{{ title }}</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.as_p }}
	              <div class="form-group">
	                <input type="submit" value="Save" class="btn btn-primary py-3 px-5">
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">{{ title }}</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
	              <div class="form-group">
	                <span style="font-size: 20px">Пароль успешно изменен, перейти в  <a href = {% url "users:profile" user.pk %}>Профиль</a></span>
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/password_reset.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">Password reset</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.as_p }}
	              <div class="form-group">
	                <input type="submit" value="Send" class="btn btn-primary py-3 px-5">
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center"></h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
	              <div class="form-group">
	                <span style="font-size: 20px">Пароль успешно изменен, <a href ={% url "users:login" %}> войти </a> в свой аккаунт </span>
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'main/base.html' %}
{% load i18n static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">Password reset</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.as_p }}
	              <div class="form-group">
	                <input type="submit" value="Save" class="btn btn-primary py-3 px-5">
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center"></h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
	              <div class="form-group">
	                <span style="font-size: 20px">Все инструкции по изменению пароля отправлены вам на почту</span>
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">{{ title }}</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.as_p }}
	              <div class="form-group">
	                <input type="submit" value="Save" class="btn btn-primary py-3 px-5">
	              </div>
					  <a href={% url "users:password_change" %}>Change password</a>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">{{ title }}</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.as_p }}
	              <div class="form-group">
	                <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}