api/urls.py
from django.urls import path, include
from .views import PostsModelViewset, UserLists
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"posts", PostsModelViewset, basename="posts")
router.register(r"users", UserLists, basename="users")

urlpatterns = [
    path("v1/", include(router.urls)),
    path("v1/drf-auth/", include("rest_framework.urls")),
]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from forum import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Сайт-журнал"

main/urls.py
from django.urls import path
from main import views
from django.core.cache import cache
from django.views.decorators.cache import cache_page


urlpatterns = [
    path("", views.index.as_view(), name="index"),
    path("post/<slug:post_slug>/", views.post.as_view(), name="post"),
    #  path(
    #      "add_comment/<slug:post_slug>/", views.add_comment, name="add_comment"
    #  ),
    path("about/", cache_page(60)(views.about.as_view()), name="about"),
    path("contact/", views.contact, name="contact"),
    path("add_post/", views.add_post.as_view(), name="add_post"),
    path("tag/<slug:tag_slug>/", views.tag_posts.as_view(), name="tag_posts"),
    path("cat/<slug:cat_slug>/", views.cat_posts.as_view(), name="cat_posts"),
    path("edit/<slug:post_slug>/", views.edit_post.as_view(), name="edit_post"),
    path("delete/<slug:post_slug>/", views.delete_post.as_view(), name="delete_post"),
]

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

app_name = "users"

urlpatterns = [
    path("login/", views.user_login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.user_register.as_view(), name="register"),
    path("register/", views.user_register.as_view(), name="register"),
    path(
        "password_change/", views.user_password_change.as_view(), name="password_change"
    ),
    path(
        "password_change_done/",
        views.user_password_change_done.as_view(),
        name="password_change_done",
    ),
    path("profile/<int:pk>", views.user_profile.as_view(), name="profile"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.contrib.auth import get_user_model


class Posts(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name="Заголовок",
        validators=[MinLengthValidator(3)],
    )
    
    content = models.TextField(blank=True, verbose_name="Содержание")
    title_photo = models.ImageField(
        blank=True,
        null=True,
        default=None,
        upload_to="photos/%Y/%m/%d/",
        verbose_name="Главное фото",
    )
    slug = models.SlugField(
        max_length=255,
        unique=True,
    )
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    tags = models.ManyToManyField(
        "Tags", blank=True, related_name="tags", verbose_name="Теги"
    )
    cats = models.ForeignKey(
        "Categories",
        blank=True,
        null=True,
        related_name="cats",
        on_delete=models.SET_NULL,
        verbose_name="Категории",
    )
    author = models.ForeignKey(get_user_model(), null = True, default = None, on_delete=models.SET_NULL, related_name="auth")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post", kwargs={"post_slug": self.slug})

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

class Tags(models.Model):
    tag_name = models.CharField(max_length=255, unique=True, verbose_name = "Назвение тега")
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.tag_name

    def get_absolute_url(self):
        return reverse("tag_posts", kwargs={"tag_slug": self.slug})

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class Categories(models.Model):
    cat_name = models.CharField(max_length=255, unique=True, verbose_name="Название категории")
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.cat_name

    def get_absolute_url(self):
        return reverse("cat_posts", kwargs={"cat_slug": self.slug})

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Comments(models.Model):
    author_name = models.CharField(max_length=255, verbose_name="Автор")
    email = models.EmailField()
    message = models.TextField(verbose_name = "Текст")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    post = models.ForeignKey(
        "Posts",
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост",
    )

    def __str__(self):
        return f"{self.author_name}, {self.email}"

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

main/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from .models import Posts, Tags, Categories, Comments
from django.shortcuts import get_object_or_404
from .forms import Add_post_form, Edit_post_form, Add_comment_form
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from .utils import DataMixin, russian_in_english
from django.core.paginator import Paginator
from django import forms
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify
from django.core.mail import send_mail
from forum import settings
from django.core.cache import cache
from . import signals
from django.core.signals import request_finished
import string

# def index(request):
#     data = {"posts": Posts.objects.all().prefetch_related("tags", "comments").select_related("cats"), "selected": "index", "cat_selected": "all_cat"}
#     return render(request, "main/index.html", data)

# class index(TemplateView):
#     template_name = "main/index.html"
#     extra_context = {
#         "posts": Posts.objects.all().prefetch_related("tags", "comments").select_related("cats"),
#         "selected": "index",
#         "cat_selected": "all_cat",
#     }

# class index(ListView):
#     template_name = "main/index.html"
#     context_object_name = "posts"
#     def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
#         context = super().get_context_data(**kwargs)
#         context["selected"] = "index"
#         context["cat_selected"] = "all_cat"
#         return context
#     def get_queryset(self) -> QuerySet[Any]:
#         queryset = (
#             Posts.objects.all()
#             .prefetch_related("tags", "comments")
#             .select_related("cats")
#         )
#         return queryset


class index(DataMixin, ListView):
    template_name = "main/index.html"
    context_object_name = "posts"
    selected = "index"
    paginate_by = 10 # передает в шаблон page_obj - объект - текущую страницу, и paginator - объект пагинатор

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return self.get_context_data_mixin(
            context, cat_selected="all_cat", filter=self.request.GET.get("filter")
        )

    def get_queryset(self) -> QuerySet[Any]:
        if self.request.GET.get("filter"):
            queryset = (
                Posts.objects.filter(title__icontains=self.request.GET.get("filter"))
                .prefetch_related("tags", "comments")
                .select_related("cats")
            )
        else:
            queryset = cache.get_or_set(
                "all_posts",
                Posts.objects.all()
                .prefetch_related("tags", "comments")
                .select_related("cats"),
                60
            )
        return queryset


# class post(DetailView):
#     model = Posts
#     template_name = "main/post.html"
#     context_object_name = "post"
#     slug_url_kwarg = "post_slug"

#     def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
#         context = super().get_context_data(**kwargs)
#         context["selected"] = "post"
#         context["post_tags"] = context["post"].tags.all()
#         context["post_comments"] = Comments.objects.filter(post=context["post"])
#         return context


class post(DataMixin, DetailView):
    model = Posts
    template_name = "main/post.html"
    context_object_name = "post"
    slug_url_kwarg = "post_slug"
    selected = "post"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return self.get_context_data_mixin(
            context,
            post_tags=cache.get_or_set("all_tags_post", context["post"].tags.all(), 60),
            post_comments=Comments.objects.filter(post=context["post"])
        )     

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context["form"] = Add_comment_form()
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = Add_comment_form(self.request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.author_name = self.request.user.username
            f.email = self.request.user.email
            f.post = self.object
            f.save()
            form = Add_comment_form()
        else: 
            form = Add_comment_form(self.request.POST)
        context["form"] = form
        return self.render_to_response(context)


#  def get_object(self, queryset = None) -> Model:
#     return get_object_or_404(Posts, slug = self.kwargs[self.slug_url_kwarg])


# def post(request, post_slug):
#     post = get_object_or_404(Posts, slug=post_slug)
#     data = {
#         "post_slug": post_slug,
#         "selected": "post",
#         "post": post,
#         "post_tags": post.tags.all(),
#         "post_comments": Comments.objects.filter(post=post),
#     }
#     return render(request, "main/post.html", data)


# def about(request):
#     data = {"selected": "about"}
#     return render(request, "main/about.html", data)

class about(DataMixin, TemplateView):
    template_name = "main/about.html"
    selected = "about"


def contact(request):
    if request.method == "POST":
        print(request.POST)
        send_mail(
            request.POST.get("name"),
            f'От организации: {request.POST.get("organization")} \n{request.POST.get("message")}',
            settings.EMAIL_HOST_USER,
            [request.POST.get("email")],
            fail_silently=False,
        )
        return redirect(request.META["HTTP_REFERER"], permanent=True)
    return render(request, "main/contact.html")


# def add_post(request):
#     if request.method == "POST":
#         form = Add_post_form(request.POST, request.FILES)
#         if form.is_valid():
#            form.save()
#            return redirect("index")

#     else:
#         form = Add_post_form()
#     data = {"selected": "add_post", "form": form}
#     return render(request, "main/add_post.html", data)

# class add_post(View):

#     def get(self, request):
#         form = Add_post_form()
#         data = {"selected": "add_post", "form": form}
#         return render(request, "main/add_post.html", data)

#     def post(self, request):
#         form = Add_post_form(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect("index")
#         else:
#            data = {"selected": "add_post", "form": form}
#            return render(request, "main/add_post.html", data)

# class add_post(FormView):
#     form_class = Add_post_form
#     template_name = "main/add_post.html"
#     success_url = reverse_lazy("index")

#     def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
#         context = super().get_context_data(**kwargs)
#         context["selected"] = "add_post"
#         return context

#     def form_valid(self, form: Any) -> HttpResponse:
#         form.save()
#         print(self.request.POST["slug"])
#         return super().form_valid(form)

#     def get_success_url(self) -> str:
#         return reverse_lazy("post", kwargs={"post_slug": self.request.POST["slug"]})

# class add_post(CreateView):
#     form_class = Add_post_form
#     template_name = "main/add_post.html"
#     success_url = reverse_lazy("index")
#     def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
#         context = super().get_context_data(**kwargs)
#         context["selected"] = "add_post"
#         context["title"] = "Add post"
#         return context


# def add_comment(request, post_slug):
#     new_request_post = request.POST.copy()
#     new_request_post["post"] = Posts.objects.get(slug=post_slug)
#     form = Add_comment_form(new_request_post)
#     if form.is_valid():
#         form.save()
#         messages.success(request, "Комментарий добавлен!")
#     else:
#         messages.error(request,"Ошибка добавления комментария")

#     return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class add_post(LoginRequiredMixin, DataMixin, CreateView):
    form_class = Add_post_form
    template_name = "main/add_post.html"
    success_url = reverse_lazy("index")
    selected = "add_post"
    title = "Add post"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return self.get_context_data_mixin(context)

    def form_valid(self, form):
        f = form.save(commit=False) # используется чтобы через форму получить объект модели и в нем прописать значение поля "автор", 
        # ибо в самой форме нет такого поля, поэтому заходим через модель
        f.author = self.request.user
        if set(self.request.POST["title"].lower()).issubset(set(string.ascii_lowercase + ' ')):
            if not Posts.objects.filter(slug=slugify(str(self.request.POST["title"]))):
                f.slug = slugify(str(self.request.POST["title"]))
            else:
                form.add_error(
                    "title",
                    forms.ValidationError(
                        "Статья с таким slug и заголовком уже существует"
                    ),
                )
                return super().form_invalid(form)
        else:
            if not Posts.objects.filter(
                slug = russian_in_english(str(self.request.POST["title"]))
            ):

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
	    	<div class="container-fluid px-0">
	    		<div class="row d-flex">
	    			<div class="col-md-6 d-flex">
	    				<div class="img d-flex align-self-stretch align-items-center js-fullheight" style="background-image:url({% static "main/images/about.jpg" %});">
	    				</div>
	    			</div>
	    			<div class="col-md-6 d-flex align-items-center">
	    				<div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
		            <h2 class="mb-4">I'm <span>Andrea Moore</span> a Scotish Blogger &amp; Explorer</h2>
		            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
	            </div>
		        </div>
	        </div>
	    	</div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

main/templates/main/add_post.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section contact-section px-md-4">
	      <div class="container">
			  <h1 class="h3" style =" text-align: center">{{ title }}</h1>
	        <div class="row block-9" style="justify-content: space-around">
	          <div class="col-lg-6 d-flex" style="flex: 0 0 70%; max-width: 70%">
	            <form action="#" class="bg-light p-5 contact-form" method = "POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form.non_field_errors }}
						{% for f in form %}
	              <div class="form-group">
						{% if f.label == "Теги" or f.label == "Изображение для главной страницы"%} <label for="{{ f.id_for_label }}">{{f.label}}: </label> 
						{% elif f.label == "Главное фото" and f.value.url %}<p><img src={{f.value.url}} style=" width:100px "><p>
						{% endif %}
	                {{f}}
	              </div>
					  {{ f.errors }}
						{% endfor %}
	              <div class="form-group">
	                <input type="submit" value="Save" class="btn btn-primary py-3 px-5">
	              </div>
	            </form>
	          </div>
	        </div>
	      </div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Andrea - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">

    <link rel="stylesheet" href={% static "main/css/open-iconic-bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "main/css/animate.css"%}>
    
    <link rel="stylesheet" href={% static "main/css/owl.carousel.min.css"%}>
    <link rel="stylesheet" href={% static "main/css/owl.theme.default.min.css"%}>
    <link rel="stylesheet" href={% static "main/css/magnific-popup.css"%}>

    <link rel="stylesheet" href={% static "main/css/aos.css"%}>
	 
    <link rel="stylesheet" href={% static "main/css/ionicons.min.css"%}>

    <link rel="stylesheet" href={% static "main/css/bootstrap-datepicker.css"%}>
    <link rel="stylesheet" href={% static "main/css/jquery.timepicker.css"%}>

    
    <link rel="stylesheet" href={% static "main/css/flaticon.css"%}>
    <link rel="stylesheet" href={% static "main/css/icomoon.css"%}>
    <link rel="stylesheet" href={% static "main/css/style.css" %}	>
  </head>
  <body>

	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="js-fullheight">
			<nav id="colorlib-main-menu" role="navigation">
				<ul>
					{% if user.is_authenticated  %}
					<li {% if selected == "Profile" %}class="colorlib-active" {% endif %}> <a href={% url "users:profile" user.pk %}> {{user.username}} | profile</a></li>
					<li> <a href={% url "users:logout" %}> logout</a></li>
					{% else %}
					<li {% if selected == 'login' %} class="colorlib-active" {% endif %}><a href={% url "users:login" %} >Login</a>
					<li {% if selected == 'Registration' %} class="colorlib-active" {% endif %}><a href={% url "users:register" %}>Registration</a></li>
					{% endif %}
					<li {% if selected == 'index' %} class="colorlib-active" {% endif %}><a href={% url "index" %}>Home</a></li>
					<li {% if selected == 'about' %} class="colorlib-active" {% endif %}><a href={% url "about" %}>About</a></li>
					<li {% if selected == 'contact' %} class="colorlib-active" {% endif %}><a href={% url "contact" %}>Contact</a></li>
					<li {% if selected == 'add_post' %} class="colorlib-active" {% endif %}><a href={% url "add_post" %}> Add post</a></li>
					{% if selected == 'edit_post' %}
					<li {% if selected == 'edit_post' %} class="colorlib-active" {% endif %}><a>Edit post</a></li>	
					{% endif %}
					{% if selected == 'post' %}
					<li {% if selected == 'post' %} class="colorlib-active" {% endif %}><a>{{ post.title }}</a></li>	
					{% endif %}
				</ul>
			</nav>
			<div class="colorlib-footer">
			

				<p class="pfooter"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with
	  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
			</div>
		</aside> <!-- END COLORLIB-ASIDE -->
	{% block content %}
	{% endblock %}
	</div><!-- END COLORLIB-PAGE -->

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src={% static "main/js/jquery.min.js" %}></script>
  <script src={% static "main/js/jquery-migrate-3.0.1.min.js" %}></script>
  <script src={% static "main/js/popper.min.js" %}></script>
  <script src={% static "main/js/bootstrap.min.js" %}></script>
  <script src={% static "main/js/jquery.easing.1.3.js" %}></script>
  <script src={% static "main/js/jquery.waypoints.min.js" %}></script>
  <script src={% static "main/js/jquery.stellar.min.js" %}></script>
  <script src={% static "main/js/owl.carousel.min.js" %}></script>
  <script src={% static "main/js/jquery.magnific-popup.min.js" %}></script>
  <script src={% static "main/js/aos.js" %}></script>
  <script src={% static "main/js/jquery.animateNumber.min.js" %}></script>
  <script src={% static "main/js/scrollax.min.js" %}></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src={% static "main/js/google-map.js" %}></script>
  <script src={% static "main/js/main.js" %}></script>
    
  </body>
</html>

main/templates/main/cats.html
<ul class="categories">
	<li><a href={% url "index" %} {% if cat_selected == "all_cat" %} style='color:#007bff' {% endif %}> All posts<span {% if cat_selected == "all_cat" %} style='color:#007bff' {% endif %}> {{ count_posts }} </span></a></li>
{% if all_cats %}
	{% for c in all_cats %}
	{% if c.cats.all %} 
	<li><a href="{{ c.get_absolute_url }}" {% if cat_selected == c %} style='color:#007bff' {% endif %}>{{c.cat_name}} <span {% if cat_selected == c %} style='color:#007bff' {% endif %}>{{ c.cats.count }}</span></a></li>
	{% endif %}
	{% endfor %}
</ul>
{% endif %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load tags %}
{% block content %}
		<div id="colorlib-main">
			<section class="ftco-section ftco-no-pt ftco-no-pb">
	    	<div class="container">
	    		<div class="row d-flex">
	    			<div class="col-xl-8 py-5 px-md-5">
	    				<div class="row pt-md-4">
								<div class="col-md-12">
									{% for p in posts %}
										<div class="blog-entry ftco-animate d-md-flex">
											<a href={{ p.get_absolute_url }} class="img img-2" style="background-image: url({% if p.title_photo %} {{ p.title_photo.url }} {% else %} {% static 'main/images/image_12.jpg' %} {% endif %});"></a>
													<div class="text text-2 pl-md-4">
														<h3 class="mb-2"><a href={{ p.get_absolute_url }}>{{p.title}}</a></h3>
														<div class="meta-wrap">
																<p class="meta">
																	<span><i class="icon-calendar mr-2"></i>{{ p.time_create|date:"d-m-Y" }} </span>
																	<span>
																	{% for t in p.tags.all %} 
																	<a href={{ t.get_absolute_url }}>{% if forloop.first %}<i class="icon-folder-o mr-2">{% endif %}</i>{{t}}</a>
																	{% if not forloop.last %},{% endif %}
																	{% endfor %}
																	</span>
																	<span><i class="icon-comment2 mr-2"></i>{{ p.comments.all.count }} Comment</span>
																</p>
														</div>
														<p class="mb-4">{{content|truncatechars:100}}</p>
														<a href={{ p.get_absolute_url }} class="btn-custom">Read <span class="ion-ios"> &nbsp&nbsp{% if user.is_authenticated and user == p.author or user.is_superuser %} / &nbsp&nbsp{% endif %}</span></a>
														{% if user.is_authenticated and user == p.author or user.is_superuser or perms.main.change_posts %}
														<a href={% url "edit_post" p.slug %} class="btn-custom">Edit <span class="ion-ios"></span></a></p>
														{% endif %}
													{% if user.is_authenticated and user == p.author or user.is_superuser or perms.main.delete_posts %}
													<form action = {% url "delete_post" p.slug %} method ="POST">{% csrf_token %} <input type="submit" value="delete" class="btn btn-primary"></form>
													{% endif %}
													</div>
										</div>
									{% endfor %}
								</div>
			    		</div><!-- END-->
			    		<div class="row">
			          <div class="col">
			            <div class="block-27">
								{% if page_obj.has_other_pages  %}
			              <ul>
								{% if page_obj.has_previous %}
			                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
								{% endif %}
								 {% for p in paginator.page_range %}
								 {% if p >= page_obj.number|add:-2  and p <= page_obj.number|add:2 %}
			                <li {% if p == page_obj.number %} class="active" {% endif %}><a href="?page={{ p }}" >{{ p }}</a></li>
								 {% endif %}
								 {% endfor %}
								{% if page_obj.has_next %}
			                <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
								{% endif %}
			              </ul>
							  {% endif %}
			            </div>
			          </div>
			        </div>
			    	</div>
	    			<div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
	            <div class="sidebar-box pt-md-4">
	              <form action="#" class="search-form" method = "GET">
	                <div class="form-group">
	                  <span class="icon icon-search"></span>
	                  <input type="text" class="form-control" name = "filter"  {% if filter %} value = {{filter}} placeholder="Type a keyword and hit enter" {% endif %} placeholder="Type a keyword and hit enter">
	                </div>
	              </form>
	            </div>
	            <div class="sidebar-box ftco-animate">
	            	<h3 class="sidebar-heading">Categories</h3>
						{% get_all_cats cat_selected %}
	            </div>
	            <div class="sidebar-box ftco-animate">
	              <h3 class="sidebar-heading">Tag Cloud</h3>
					  {% get_all_tags tag_selected %}
	            </div>
	            <div class="sidebar-box ftco-animate">
	              <h3 class="sidebar-heading">Paragraph</h3>
	              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut.</p>
	            </div>
	          </div><!-- END COL -->
	    		</div>
	    	</div>
	    </section>
		 
		</div>

{% endblock %}